# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 511)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("color: rgb(35, 15, 255);\n"
"background-color: rgb(240, 240, 240);")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 411))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.tabWidget.setObjectName("tabWidget")
        self.shellmanage = QtWidgets.QWidget()
        self.shellmanage.setObjectName("shellmanage")
        self.listWidget = QtWidgets.QListWidget(self.shellmanage)
        self.listWidget.setGeometry(QtCore.QRect(-2, 0, 521, 391))
        self.listWidget.setStyleSheet("")
        self.listWidget.setIconSize(QtCore.QSize(0, 0))
        self.listWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.textEdit_2 = QtWidgets.QTextEdit(self.shellmanage)
        self.textEdit_2.setGeometry(QtCore.QRect(518, 0, 121, 391))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget.addTab(self.shellmanage, "")
        self.filemanage = QtWidgets.QWidget()
        self.filemanage.setObjectName("filemanage")
        self.treeWidget = QtWidgets.QTreeWidget(self.filemanage)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 161, 391))
        self.treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.filemanage)
        self.treeWidget_2.setGeometry(QtCore.QRect(160, 0, 481, 391))
        self.treeWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget_2.setAnimated(False)
        self.treeWidget_2.setAllColumnsShowFocus(False)
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.treeWidget_2.header().setCascadingSectionResizes(True)
        self.treeWidget_2.header().setDefaultSectionSize(126)
        self.treeWidget_2.header().setMinimumSectionSize(25)
        self.tabWidget.addTab(self.filemanage, "")
        self.terminal = QtWidgets.QWidget()
        self.terminal.setObjectName("terminal")
        self.textEdit = QtWidgets.QTextEdit(self.terminal)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 641, 351))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.terminal)
        self.lineEdit.setGeometry(QtCore.QRect(0, 350, 431, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(249, 249, 249);")
        self.lineEdit.setObjectName("lineEdit")
        self.zhixing = QtWidgets.QPushButton(self.terminal)
        self.zhixing.setGeometry(QtCore.QRect(430, 350, 101, 41))
        self.zhixing.setObjectName("zhixing")
        self.clearbutton = QtWidgets.QPushButton(self.terminal)
        self.clearbutton.setGeometry(QtCore.QRect(529, 350, 111, 41))
        self.clearbutton.setObjectName("clearbutton")
        self.tabWidget.addTab(self.terminal, "")
        self.script = QtWidgets.QWidget()
        self.script.setObjectName("script")
        self.textEdit_3 = QtWidgets.QTextEdit(self.script)
        self.textEdit_3.setGeometry(QtCore.QRect(0, 0, 641, 351))
        self.textEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(170, 0, 255);")
        self.textEdit_3.setTabChangesFocus(False)
        self.textEdit_3.setObjectName("textEdit_3")
        self.savejiaoben = QtWidgets.QPushButton(self.script)
        self.savejiaoben.setGeometry(QtCore.QRect(-1, 350, 321, 41))
        self.savejiaoben.setObjectName("savejiaoben")
        self.clearjiaoben = QtWidgets.QPushButton(self.script)
        self.clearjiaoben.setGeometry(QtCore.QRect(318, 350, 321, 41))
        self.clearjiaoben.setObjectName("clearjiaoben")
        self.tabWidget.addTab(self.script, "")
        self.database = QtWidgets.QWidget()
        self.database.setObjectName("database")
        self.textEdit_4 = QtWidgets.QTextEdit(self.database)
        self.textEdit_4.setGeometry(QtCore.QRect(0, 0, 641, 391))
        self.textEdit_4.setTabChangesFocus(False)
        self.textEdit_4.setObjectName("textEdit_4")
        self.tabWidget.addTab(self.database, "")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 416, 631, 83))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.adduser = QtWidgets.QPushButton(self.layoutWidget)
        self.adduser.setObjectName("adduser")
        self.gridLayout.addWidget(self.adduser, 1, 0, 1, 1)
        self.format = QtWidgets.QPushButton(self.layoutWidget)
        self.format.setObjectName("format")
        self.gridLayout.addWidget(self.format, 0, 2, 1, 1)
        self.exit = QtWidgets.QPushButton(self.layoutWidget)
        self.exit.setObjectName("exit")
        self.gridLayout.addWidget(self.exit, 1, 5, 1, 1)
        self.chinese = QtWidgets.QPushButton(self.layoutWidget)
        self.chinese.setObjectName("chinese")
        self.gridLayout.addWidget(self.chinese, 0, 3, 1, 1)
        self.shutdown = QtWidgets.QPushButton(self.layoutWidget)
        self.shutdown.setObjectName("shutdown")
        self.gridLayout.addWidget(self.shutdown, 1, 1, 1, 1)
        self.open3389 = QtWidgets.QPushButton(self.layoutWidget)
        self.open3389.setObjectName("open3389")
        self.gridLayout.addWidget(self.open3389, 1, 2, 1, 1)
        self.passwd = QtWidgets.QPushButton(self.layoutWidget)
        self.passwd.setObjectName("passwd")
        self.gridLayout.addWidget(self.passwd, 0, 1, 1, 1)
        self.loveme = QtWidgets.QPushButton(self.layoutWidget)
        self.loveme.setObjectName("loveme")
        self.gridLayout.addWidget(self.loveme, 0, 5, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 4, 1, 1)
        self.update = QtWidgets.QPushButton(self.layoutWidget)
        self.update.setObjectName("update")
        self.gridLayout.addWidget(self.update, 1, 4, 1, 1)
        self.homepage = QtWidgets.QPushButton(self.layoutWidget)
        self.homepage.setObjectName("homepage")
        self.gridLayout.addWidget(self.homepage, 1, 3, 1, 1)
        self.user = QtWidgets.QPushButton(self.layoutWidget)
        self.user.setStyleSheet("")
        self.user.setObjectName("user")
        self.gridLayout.addWidget(self.user, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 491, 61, 21))
        self.label.setObjectName("label")
        self.connectlabel = QtWidgets.QLabel(self.centralwidget)
        self.connectlabel.setGeometry(QtCore.QRect(20, 493, 60, 16))
        self.connectlabel.setAutoFillBackground(False)
        self.connectlabel.setObjectName("connectlabel")
        self.shelllabel = QtWidgets.QLabel(self.centralwidget)
        self.shelllabel.setGeometry(QtCore.QRect(79, 491, 361, 20))
        self.shelllabel.setText("")
        self.shelllabel.setObjectName("shelllabel")
        self.timelabel = QtWidgets.QLabel(self.centralwidget)
        self.timelabel.setGeometry(QtCore.QRect(501, 492, 121, 20))
        self.timelabel.setText("")
        self.timelabel.setObjectName("timelabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python knife    by  qianxiao996"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "                                  shell 地 址                                      密码"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shellmanage), _translate("MainWindow", "shell管理"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "        目 录 列 表"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "       文件名"))
        self.treeWidget_2.headerItem().setText(1, _translate("MainWindow", "    修改时间"))
        self.treeWidget_2.headerItem().setText(2, _translate("MainWindow", "   权限"))
        self.treeWidget_2.headerItem().setText(3, _translate("MainWindow", "   大小"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.filemanage), _translate("MainWindow", "文件管理"))
        self.zhixing.setText(_translate("MainWindow", "执   行"))
        self.clearbutton.setText(_translate("MainWindow", "清   空"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.terminal), _translate("MainWindow", "虚拟终端"))
        self.savejiaoben.setText(_translate("MainWindow", "保 存 脚 本"))
        self.clearjiaoben.setText(_translate("MainWindow", "清 空 脚 本"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.script), _translate("MainWindow", "自写脚本"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.database), _translate("MainWindow", "数据库管理"))
        self.adduser.setText(_translate("MainWindow", "添加用户"))
        self.format.setText(_translate("MainWindow", "格式化c盘"))
        self.exit.setText(_translate("MainWindow", "退出程序"))
        self.chinese.setText(_translate("MainWindow", "中文检测"))
        self.shutdown.setText(_translate("MainWindow", "强制关机"))
        self.open3389.setText(_translate("MainWindow", "开启3389"))
        self.passwd.setText(_translate("MainWindow", "修改密码"))
        self.loveme.setText(_translate("MainWindow", "联系作者"))
        self.pushButton.setText(_translate("MainWindow", "待添加"))
        self.update.setText(_translate("MainWindow", "检查更新"))
        self.homepage.setText(_translate("MainWindow", "待添加"))
        self.user.setText(_translate("MainWindow", "查询用户"))
        self.label.setText(_translate("MainWindow", "当前时间："))
        self.connectlabel.setText(_translate("MainWindow", "当前连接："))

